title: Sahithyen's Blog
email: sahithyen@me.com
description: Sahithyen's personal blog
url: "https://blog.sahithyen.com/"
permalink: /:month/:year/:title/

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
